# Generated by Django 3.1.13 on 2022-04-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracesource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weakpassword',
            name='account',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='账号'),
        ),
    ]
