# Generated by Django 3.1.13 on 2022-04-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracesource', '0002_weakpassword_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directoryblast',
            name='status_code',
        ),
        migrations.AddField(
            model_name='directoryblast',
            name='dirs',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='状态码'),
        ),
    ]
