# Generated by Django 3.1.13 on 2022-04-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracesource', '0003_auto_20220419_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webserver',
            name='fingerprint',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='指纹'),
        ),
    ]
