# Generated by Django 3.1.13 on 2022-04-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracesource', '0004_auto_20220420_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryblast',
            name='search_code_str',
            field=models.TextField(blank=True, null=True, verbose_name='搜索状态码'),
        ),
        migrations.AddField(
            model_name='directoryblast',
            name='search_dir_str',
            field=models.TextField(blank=True, null=True, verbose_name='搜索路径'),
        ),
    ]
