# Generated by Django 3.1.13 on 2022-05-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracesource', '0006_tsserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsserver',
            name='cup_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CPU使用率'),
        ),
        migrations.AddField(
            model_name='tsserver',
            name='mem_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='内存使用率'),
        ),
    ]
