# Generated by Django 3.1.13 on 2022-05-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracesource', '0008_auto_20220525_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weakpassword',
            name='port',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='端口号'),
        ),
    ]
