# Generated by Django 3.1.13 on 2021-11-12 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_ip', models.GenericIPAddressField(verbose_name='IP')),
                ('trace_rate', models.FloatField(blank=True, default=0, null=True, verbose_name='溯源成功率')),
                ('attack_earliest_time', models.DateTimeField(blank=True, null=True, verbose_name='攻击最早时间')),
            ],
            options={
                'verbose_name': '攻击日志',
                'verbose_name_plural': '攻击日志',
                'db_table': 'alarm_attack',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AttackWhite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('white_ip', models.CharField(max_length=100, verbose_name='白名单IP')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '攻击白名单',
                'verbose_name_plural': '攻击白名单',
                'db_table': 'alarm_white',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='附件名字')),
                ('event_file', models.FileField(upload_to='files/%Y/%m/%d', verbose_name='附件地址')),
            ],
            options={
                'verbose_name': '事件附件',
                'verbose_name_plural': '事件附件',
                'db_table': 'alarm_event_file',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='佐证图片')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '佐证图片',
                'verbose_name_plural': '佐证图片',
                'db_table': 'alarm_evidence_image',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Hacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('sex', models.PositiveSmallIntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('occupation', models.CharField(blank=True, max_length=50, null=True, verbose_name='职业')),
                ('native_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='籍贯')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='位置')),
                ('network_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='网络ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮件')),
                ('qq', models.CharField(blank=True, max_length=50, null=True, verbose_name='邮件')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='手机号')),
                ('id_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='身份证号')),
                ('other_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='其他身份信息')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='照片')),
                ('photo_source', models.CharField(blank=True, max_length=50, null=True, verbose_name='照片来源')),
                ('fingerprint_info', models.JSONField(blank=True, default=list, null=True, verbose_name='指纹信息')),
                ('attack_ip', models.JSONField(blank=True, default=list, null=True, verbose_name='攻击IP')),
                ('attack_type', models.JSONField(blank=True, default=list, null=True, verbose_name='攻击手法')),
                ('virus_sample', models.JSONField(blank=True, default=list, null=True, verbose_name='关联病毒')),
                ('domain', models.JSONField(blank=True, default=list, null=True, verbose_name='关联域名')),
                ('other_facilities', models.JSONField(blank=True, default=list, null=True, verbose_name='其他设施')),
                ('evidence_image', models.ManyToManyField(related_name='hacker_evidence', to='alarm.EvidenceImage', verbose_name='佐证图片')),
            ],
            options={
                'verbose_name': '黑客',
                'verbose_name_plural': '黑客',
                'db_table': 'alarm_hacker',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='事件标题')),
                ('event_file', models.ManyToManyField(to='alarm.EventFile')),
                ('hacker', models.ManyToManyField(to='alarm.Hacker')),
            ],
            options={
                'verbose_name': '事件',
                'verbose_name_plural': '事件',
                'db_table': 'alarm_event',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AttackDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attack_time', models.DateTimeField(verbose_name='攻击时间')),
                ('destination_ip', models.CharField(max_length=255, verbose_name='攻击目标目的IP')),
                ('attack_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='攻击类型')),
                ('source', models.CharField(blank=True, max_length=20, null=True, verbose_name='来源')),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_details', to='alarm.attack', verbose_name='攻击日志')),
            ],
            options={
                'verbose_name': '攻击日志详情',
                'verbose_name_plural': '攻击日志详情',
                'db_table': 'alarm_attack_details',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='attack',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alarm.event'),
        ),
        migrations.AddField(
            model_name='attack',
            name='hacker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alarm.hacker'),
        ),
    ]
