# Generated by Django 3.1.13 on 2021-11-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailTagInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_info', models.JSONField(blank=True, default=list, null=True, verbose_name='标签信息')),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_tag_info', to='alarm.attack', verbose_name='攻击日志')),
            ],
            options={
                'verbose_name': '攻击详情-标签信息',
                'verbose_name_plural': '攻击详情-标签信息',
                'db_table': 'alarm_detail_tag_info',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DetailDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.JSONField(blank=True, default=list, null=True, verbose_name='备案信息')),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_domain', to='alarm.attack', verbose_name='攻击日志')),
            ],
            options={
                'verbose_name': '攻击详情-域名备案',
                'verbose_name_plural': '攻击详情-域名备案',
                'db_table': 'alarm_detail_domain',
                'ordering': ['-id'],
            },
        ),
    ]
