# Generated by Django 3.1.13 on 2021-11-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0003_detaillocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaillocation',
            name='location',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='地理位置信息'),
        ),
        migrations.AlterField(
            model_name='detailtaginfo',
            name='tag_info',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='标签信息'),
        ),
    ]
