# Generated by Django 3.1.13 on 2021-11-24 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0004_auto_20211116_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='FofaToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=255, verbose_name='邮箱')),
                ('key', models.CharField(max_length=255, verbose_name='邮箱')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, '未知'), (1, '正常'), (2, '异常')], default=0, null=True, verbose_name='状态')),
                ('error_msg', models.CharField(blank=True, max_length=255, null=True, verbose_name='错误信息')),
                ('error_num', models.IntegerField(default=0, help_text='错误次数', validators=[django.core.validators.MinValueValidator(0)], verbose_name='异常次数')),
                ('status_change_at', models.DateTimeField(blank=True, null=True, verbose_name='状态改变时间')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'FofaToken',
                'verbose_name_plural': 'FofaToken',
                'db_table': 'passive_fofa_token',
                'ordering': ['-id'],
                'unique_together': {('email', 'key')},
            },
        ),
    ]
