# Generated by Django 3.1.13 on 2021-11-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0006_xtbapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xtbapikey',
            name='apikey',
            field=models.CharField(max_length=255, unique=True, verbose_name='ApiKey'),
        ),
        migrations.AlterField(
            model_name='xtbapikey',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户名'),
        ),
    ]
