# Generated by Django 3.1.13 on 2022-03-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0011_detailtaginfo_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='domain_num',
            field=models.ImageField(default=0, upload_to='', verbose_name='域名数量'),
        ),
    ]
