# Generated by Django 3.1.13 on 2022-03-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0012_attack_domain_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='domain_num',
            field=models.IntegerField(default=0, verbose_name='域名数量'),
        ),
    ]
