# Generated by Django 3.1.13 on 2022-04-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0013_auto_20220330_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地理位置'),
        ),
    ]
