# Generated by Django 3.1.13 on 2022-04-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0014_attack_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='location',
            field=models.JSONField(blank=True, null=True, verbose_name='地理位置'),
        ),
    ]
