# Generated by Django 3.1.13 on 2022-04-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0015_auto_20220406_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='asset_num',
            field=models.IntegerField(default=0, verbose_name='资产数量'),
        ),
    ]
