# Generated by Django 3.1.13 on 2022-04-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0016_attack_asset_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='is_tag_info',
            field=models.BooleanField(default=False, verbose_name='标签'),
        ),
    ]
