# Generated by Django 3.1.13 on 2022-04-11 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0017_attack_is_tag_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='NsfocusApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apikey', models.CharField(max_length=255, unique=True, verbose_name='ApiKey')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, '未知'), (1, '正常'), (2, '异常'), (3, '失效')], default=0, null=True, verbose_name='状态')),
                ('error_msg', models.CharField(blank=True, max_length=255, null=True, verbose_name='错误信息')),
                ('error_num', models.IntegerField(default=0, help_text='错误次数', validators=[django.core.validators.MinValueValidator(0)], verbose_name='异常次数')),
                ('status_change_at', models.DateTimeField(blank=True, null=True, verbose_name='状态改变时间')),
                ('api_limit', models.IntegerField(default=50, verbose_name='API限制')),
                ('api_remaining', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='API剩余')),
                ('api_reset_at', models.DateTimeField(blank=True, null=True, verbose_name='重置时间')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'NsfocusApiKey',
                'verbose_name_plural': 'NsfocusApiKey',
                'db_table': 'passive_nsfocus_apikey',
                'ordering': ['-id'],
            },
        ),
    ]
