# Generated by Django 3.1.13 on 2022-04-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0018_nsfocusapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='intel_types',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='IP属性'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='is_tag_info',
            field=models.BooleanField(default=False, verbose_name='是否搜索过标签'),
        ),
    ]
