# Generated by Django 3.1.13 on 2022-04-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0019_auto_20220424_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='is_malicious',
            field=models.BooleanField(default=False, verbose_name='是否是恶意'),
        ),
    ]
