# Generated by Django 3.1.13 on 2022-04-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0020_attack_is_malicious'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='is_malicious',
        ),
        migrations.AddField(
            model_name='attack',
            name='malicious',
            field=models.SmallIntegerField(choices=[(0, '未知'), (1, '恶意'), (2, '非恶意')], db_index=True, default=0, verbose_name='恶意'),
        ),
    ]
