# Generated by Django 3.1.13 on 2022-04-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0021_auto_20220424_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='is_ip_query',
            field=models.BooleanField(default=False, verbose_name='是否搜索过ip分析'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='is_tag_info',
            field=models.BooleanField(default=False, verbose_name='是否搜索过标签/信誉'),
        ),
    ]
