# Generated by Django 3.1.13 on 2022-04-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0022_auto_20220424_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attack',
            old_name='intel_types',
            new_name='judgments',
        ),
    ]
