# Generated by Django 3.1.13 on 2022-04-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0023_auto_20220424_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtaginfo',
            name='ports',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='端口信息'),
        ),
    ]
