# Generated by Django 3.1.13 on 2022-04-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0024_detailtaginfo_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtaginfo',
            name='cur_domains',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='domains信息'),
        ),
        migrations.AddField(
            model_name='detailtaginfo',
            name='history_domains',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='history_domains信息'),
        ),
    ]
