# Generated by Django 3.1.13 on 2022-04-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0025_auto_20220424_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtaginfo',
            name='history_domains',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='history_domains信息'),
        ),
    ]
