# Generated by Django 3.1.13 on 2022-04-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0026_auto_20220424_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='trace_rate',
            field=models.FloatField(blank=True, default=0.3, null=True, verbose_name='溯源成功率'),
        ),
    ]
