# Generated by Django 3.1.13 on 2022-05-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0027_auto_20220428_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='fz_task_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='反制任务id'),
        ),
    ]
