# Generated by Django 3.1.13 on 2022-05-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0029_attack_fz_result_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='fz_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='反制任务结束时间'),
        ),
        migrations.AddField(
            model_name='attack',
            name='fz_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='反制任务开始时间'),
        ),
    ]
