# Generated by Django 3.1.13 on 2022-05-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0031_icpzoomeyetoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IcpZoomEyeToken',
            new_name='ZoomEyeToken',
        ),
    ]
