# Generated by Django 3.1.13 on 2022-05-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0032_auto_20220511_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='is_ip2_domian',
            field=models.BooleanField(default=False, verbose_name='是否搜索过ip2域名'),
        ),
    ]
