# Generated by Django 3.1.13 on 2022-05-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0033_attack_is_ip2_domian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attack',
            old_name='is_ip2_domian',
            new_name='is_ip2_domain',
        ),
    ]
