# Generated by Django 3.1.13 on 2022-05-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0034_auto_20220512_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='vul_num',
            field=models.IntegerField(default=0, verbose_name='漏洞数量'),
        ),
    ]
