# Generated by Django 3.1.13 on 2022-04-21 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRunHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(max_length=30, verbose_name='app名称')),
                ('request_data', models.JSONField(default=dict, verbose_name='请求数据')),
                ('response_data', models.JSONField(default=dict, verbose_name='响应数据')),
                ('is_success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'APP运行历史记录',
                'verbose_name_plural': 'APP运行历史记录',
                'db_table': 'syfz_p_app_history',
                'ordering': ['-id'],
            },
        ),
    ]
