# Generated by Django 3.1.13 on 2022-04-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprunhistory',
            name='is_success',
        ),
        migrations.AddField(
            model_name='apprunhistory',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '异常'), (1, '成功'), (2, '失败')], default=1, verbose_name='是否成功'),
        ),
    ]
