# Generated by Django 3.1.13 on 2022-03-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cst_create', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('cst_modified', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='key')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('value', models.BooleanField(blank=True, default=dict, null=True, verbose_name='值')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '全局配置/开关',
                'verbose_name_plural': '全局配置/开关',
                'db_table': 'syfz_global_conf',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
    ]
