# Generated by Django 3.1.13 on 2022-03-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20220330_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfig',
            name='value',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='值'),
        ),
    ]
