# Generated by Django 3.1.13 on 2022-04-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_loginevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginevent',
            name='login_status',
            field=models.SmallIntegerField(db_index=True, default=1, verbose_name='登录状态'),
        ),
        migrations.AddField(
            model_name='loginevent',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='login_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='登录时间'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='用户名'),
        ),
    ]
