# Generated by Django 3.1.13 on 2022-04-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20220418_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginevent',
            name='login_status',
            field=models.SmallIntegerField(choices=[(0, '未知'), (1, '登录成功'), (2, '登录失败')], db_index=True, default=1, verbose_name='登录状态'),
        ),
    ]
