# Generated by Django 3.1.13 on 2022-04-25 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20220418_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_modular', models.CharField(blank=True, max_length=64, null=True, verbose_name='请求模块')),
                ('request_path', models.CharField(blank=True, max_length=400, null=True, verbose_name='请求地址')),
                ('request_body', models.TextField(blank=True, null=True, verbose_name='请求参数')),
                ('request_method', models.CharField(blank=True, max_length=64, null=True, verbose_name='请求方式')),
                ('request_msg', models.TextField(blank=True, null=True, verbose_name='操作说明')),
                ('request_ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='请求ip地址')),
                ('request_browser', models.CharField(blank=True, max_length=64, null=True, verbose_name='请求浏览器')),
                ('request_location', models.CharField(blank=True, max_length=64, null=True, verbose_name='操作地点')),
                ('request_os', models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统')),
                ('response_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='响应状态码')),
                ('response_data', models.TextField(blank=True, null=True, verbose_name='返回信息')),
                ('status', models.BooleanField(default=False, verbose_name='响应状态')),
                ('handle_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='操作类型')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'syfz_sys_operation_log',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='loginevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
