# Generated by Django 3.1.13 on 2022-04-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20220425_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modular_name', models.CharField(max_length=50, verbose_name='模块名称')),
                ('url_path', models.CharField(max_length=255, verbose_name='接口地址')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10, verbose_name='请求方式')),
                ('is_show', models.BooleanField(default=1, verbose_name='是否显示')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '请求模块',
                'verbose_name_plural': '请求模块',
                'db_table': 'syfz_sys_modular',
                'ordering': ['-id'],
            },
        ),
    ]
