# Generated by Django 3.1.13 on 2022-04-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_modular'),
    ]

    operations = [
        migrations.AddField(
            model_name='modular',
            name='handle_type',
            field=models.CharField(default=1, max_length=20, verbose_name='操作类型'),
            preserve_default=False,
        ),
    ]
