# Generated by Django 3.1.13 on 2022-04-15 11:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220414_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
