# Generated by Django 3.1.13 on 2022-04-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='key',
            new_name='secret',
        ),
    ]
